title: Giovanni Pegoraro
logo: /assets/img/logo.jpg
email: giovipegoraro@gmail.com
description: Computer Eng. BSc @ PoliMi. ROS2 dev @ PoliSpace.
favicon: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

url: "https://giovipeg.github.io/"

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/giovipeg
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/giovanni-pegoraro
  - name: Medium
    icon: <i class="fa-brands fa-medium"></i>
    link: https://medium.com/@giovipegoraro
  - name: Projects
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./projects
  - name: CV
    icon: <i class="fa-solid fa-file-pdf"></i>
    link: ./cv
